"""
config_optimised.py - Configuration generated by robust optimisation.
These are the optimal parameters found through walk-forward validation.
"""

from datetime import datetime
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = os.path.join(BASE_DIR, "logs")

# Asset universe
TICKERS = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'META', 'NVDA', 'JPM', 'JNJ', 'XOM', 'SPY', 'QQQ', 'EFA', 'EEM', 'TLT', 'LQD', 'GLD', 'DBC']

# Data period
START_DATE = "2010-01-01"
END_DATE = datetime.now().strftime("%Y-%m-%d")
INITIAL_CAPITAL = 100.0

# ---------------------------------------------------------------------------
# Optimal parameters (from robust optimisation)
# ---------------------------------------------------------------------------

LOOKBACK_DAYS = 285
REBALANCE_MIN_DAYS = 60
REBALANCE_MAX_DAYS = 90
DRIFT_THRESHOLD = 0.057
RELATIVE_TAKE_PROFIT_PCT = 0.15

RISK_FREE_RATE = 0.045
TRANSACTION_COST_PCT = 0.004
CASH_MIN_VOLATILITY = 0.25
CASH_MAX_VOLATILITY = 0.5
CASH_MAX_ALLOCATION = 0.2
DATA_BUFFER_DAYS = 400
CASH_INTEREST_RATE = 0.0525

# Logging
PORTFOLIO_LOG_FILE = "portfolio_log.csv"
REBALANCE_LOG_FILE = "rebalance_log.csv"
LAST_REBALANCE_FILE = "last_rebalance.txt"
REBALANCE_DECISIONS_FILE = "rebalance_decisions.csv"

# ---------------------------------------------------------------------------
# Optimisation metadata
# ---------------------------------------------------------------------------

# Parameters found using:
# - Walk-Forward Cross-Validation (5 folds)
# - Bayesian Optimisation (80 calls per fold)
# - Polynomial Fitting (degree 4)
# - Robustness Testing (score: 100.0%)
# - Cash Interest Rate: 5.25% AER (compounded daily)

# Fold Results:
#   Fold 1: Sharpe=0.116, Return=5.41%, DD=-13.41%
#   Fold 2: Sharpe=0.449, Return=16.31%, DD=-27.52%
#   Fold 3: Sharpe=3.460, Return=33.69%, DD=-3.09%
#   Fold 4: Sharpe=-0.610, Return=-11.72%, DD=-29.12%
#   Fold 5: Sharpe=3.334, Return=27.48%, DD=-3.22%
