"""
config_optimised.py - Configuration generated by robust optimisation.
These are the OPTIMAL parameters found through walk-forward validation.
"""

import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = os.path.join(BASE_DIR, "logs")

# Asset universe
TICKERS = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'META', 'NVDA', 'JPM', 'JNJ', 'XOM', 'SPY', 'QQQ', 'EFA', 'EEM', 'TLT', 'LQD', 'GLD', 'DBC']

# Data period
START_DATE = "2010-01-01"
END_DATE = "2024-12-30"
INITIAL_CAPITAL = 100.0

# ============================================================================
# OPTIMAL PARAMETERS (from robust optimisation)
# ============================================================================

LOOKBACK_DAYS = 290
REBALANCE_MIN_DAYS = 55
REBALANCE_MAX_DAYS = 85
DRIFT_THRESHOLD = 0.035
STOP_LOSS_PCT = 1.0
RELATIVE_TAKE_PROFIT_PCT = 0.174

RISK_FREE_RATE = 0.045
TRANSACTION_COST_PCT = 0.004
CASH_MIN_VOLATILITY = 0.25
CASH_MAX_VOLATILITY = 0.5
CASH_MAX_ALLOCATION = 0.2
DATA_BUFFER_DAYS = 400
CASH_INTEREST_RATE = 0.0525

# Logging
PORTFOLIO_LOG_FILE = "portfolio_log.csv"
REBALANCE_LOG_FILE = "rebalance_log.csv"
LAST_REBALANCE_FILE = "last_rebalance.txt"
REBALANCE_DECISIONS_FILE = "rebalance_decisions.csv"

# ============================================================================
# OPTIMISATION METADATA
# ============================================================================

# Parameters found using:
# - Walk-Forward Cross-Validation (5 folds)
# - Bayesian Optimisation (80 calls per fold)
# - Polynomial Fitting (degree 4)
# - Robustness Testing (score: 100.0%)
# - Cash Interest Rate: 5.25% AER (compounded daily)

# Fold Results:
#   Fold 1: Sharpe=0.116, Return=5.41%, DD=-13.41%
#   Fold 2: Sharpe=0.852, Return=27.11%, DD=-28.00%
#   Fold 3: Sharpe=3.330, Return=31.16%, DD=-3.35%
#   Fold 4: Sharpe=-0.679, Return=-12.96%, DD=-31.60%
#   Fold 5: Sharpe=2.700, Return=22.91%, DD=-2.78%
